plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-kapt'
    id 'com.google.dagger.hilt.android'
}

android {
    namespace 'com.planner.test.android'
    compileSdk 35

    defaultConfig {
        minSdk 33
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {
    implementation project(path: ':core:data')
    implementation project(path: ':core:ui')

    implementation 'androidx.core:core-ktx:1.15.0'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.fragment:fragment-ktx:1.8.5'
    implementation 'androidx.room:room-runtime:2.6.1'

    api 'androidx.navigation:navigation-testing:2.8.6'
    api 'androidx.test:core-ktx:1.6.1'
    api 'androidx.test:rules:1.6.1'
    api 'androidx.test:runner:1.6.1'
    api 'androidx.test.ext:junit:1.2.1'
    api 'androidx.test.espresso:espresso-core:3.6.1'
    api 'androidx.test.espresso:espresso-contrib:3.6.1'
    api "com.google.dagger:hilt-android-testing:2.50"

    implementation "com.google.dagger:hilt-android:2.50"
    kapt "com.google.dagger:hilt-compiler:2.50"
}

kapt {
    correctErrorTypes true
}
